version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "8090:8090"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgres
  app1:
    image: nachowo/cleanperfect:latest
    container_name: app1
    ports:
      - "8091:8090"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
    deploy:
      restart_policy:
        condition: on-failure
